### ISSUE TITLE
Get rid the random Jar Jar Binks response

### ISSUE THREAD

**Issue by craigcook** [mozilla/standup-irc#44]
I find it offensive. Jar Jar Binks is directly responsible for the rise of the oppressive Galactic Empire and should not be celebrated.

**Comment by willkg** [comment]
@craigcook It should be an easy change. If you want to do it and submit a PR, go for it. The code is here:

https://github.com/mozilla/standup-irc/blob/4721b8f51c5f3845c8c69a67d34ab80e6493e8ae/standup-irc.js#L438

If not, I'll do it after v2 is out.

**Comment by craigcook** [comment]
This was mostly a joke issue ;) But Random Jar Jar *is* annoying, and a bit dated. I might submit a PR replacing it with a more timeless/less obnoxious pop culture reference.

**Comment by willkg** [comment]
"Winter is coming."
"There's always money in the banana stand."
"I'm Batman."

**Comment by willkg** [comment]
@dylanwh fixed it in #51 by removing the random bits altogether.

I still think it'd be fun to have "Winter is coming." But ... maybe another bot another time.

**Comment by craigcook** [comment]
I'll submit a new joke issue: "Add a random Ned Stark response." 🐺
