### ISSUE TITLE
standups bot is non-responsive this morning

### ISSUE THREAD

**Issue by chutten** [mozilla/standup-irc#52]
Trying to talk to standups in the last twenty or so minutes and I'm getting no reply. The updates also aren't making it to the website. Tried on irc.mozilla.org #fce and #perf

Not sure what's up.

**Comment by willkg** [comment]
Looks like the bot is bouncing on and off. It's probably related to #42.

Assuming that theory is right, it'll eventually figure itself out. I'll watch the logs for a bit and see what happens.

**Comment by chutten** [comment]
It responded back to my latest salvo, so I'm content to close this and move on.

**Comment by willkg** [comment]
Sorry about that!
