### ISSUE TITLE
standups in #fce isn't working, says "Uh oh, something went wrong."

### ISSUE THREAD

**Issue by chutten** [mozilla/standup-irc#53]
Seems to come from https://github.com/mozilla/standup-irc/blob/f79f19ae30d9f61f8f79bbe96be57ad94c70f31e/standup-irc.js#L411 which means there was an error trying to post a status.

**Comment by pmac** [comment]
I believe this is due to some outages at [AWS](http://status.aws.amazon.com/) and [Heroku](https://status.heroku.com/) today. I'll check in on this when their status pages turn green again.

**Comment by willkg** [comment]
standups is working for me in the channels I'm in now. I checked logs on heroku and it has a bunch of these:

> `2017-02-28T21:11:40.459976+00:00 app[worker.1]: error: xxxxx: 503 "<!DOCTYPE html>\n\t<html>\n\t  <head>\n\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\t\t<meta charset=\"utf-8\">\n\t\t<title>Application Error</title>\n\t\t<style media=\"screen\">\n\t\t  html,body,iframe {\n\t\t\tmargin: 0;\n\t\t\tpadding: 0;\n\t\t  }\n\t\t  html,body {\n\t\t\theight: 100%;\n\t\t\toverflow: hidden;\n\t\t  }\n\t\t  iframe {\n\t\t\twidth: 100%;\n\t\t\theight: 100%;\n\t\t\tborder: 0;\n\t\t  }\n\t\t</style>\n\t  </head>\n\t  <body>\n\t\t<iframe src=\"//www.herokucdn.com/error-pages/application-error.html\"></iframe>\n\t  </body>\n\t</html>"`

That feels like outage to me.

**Comment by chutten** [comment]
Yup, looking good now that s3's back.
